AddMainPage
POWER-OF-YOUTH/graph-app-client pull request #1
Opened 2021-03-13 09:59 UTC by Dr-Positive

2021-03-13 10:02 UTC, evgeni2306 reviewed
Norm

2021-03-13 14:26 UTC, Aceki requested changes
Нужно кое-что поправить.

2021-03-13 14:26 UTC, Aceki commented on src/App.js
> +    </AppBar>
Главная страница должна формироваться в отдельном файле, располеженном по пути "pages/MainPage.js"
Пример App.js: https://github.com/POWER-OF-YOUTH/GraphApp-Legacy/blob/master/client/src/App.js

2021-03-13 14:26 UTC, Aceki commented on src/pages/LoginPage.js
> +import { Paper, Container, TextField, makeStyles, Typography, Button } from '@material-ui/core';
LoginPage.js - лишний файл.

2021-03-13 14:26 UTC, Aceki commented on src/pages/RegisterPage.js
> +import { Paper, Container, TextField, makeStyles, Typography, Button } from '@material-ui/core';
RegisterPage.js - лиший файл.

2021-03-13 14:26 UTC, Aceki commented on src/pages/MainPage.js
> +function App() {
Этот компонент следует назвать "MainPage".

2021-04-01 07:29 UTC, Aceki reviewed
Нужно обновить '.gitignore'.

2021-04-01 07:29 UTC, Aceki commented on .vscode/launch.json
> +{
Лишний файл. Директорию нужно добавить в файл '.gitignore' и удалить из репозитория.

2021-04-01 07:29 UTC, Aceki commented on package-lock.json
> +{
Этот файл тоже лучше добавить в '.gitignore'.

2021-07-17 15:32 UTC, merged